title: RobuO
description: Intelligent Robotics and Control at uOttawa

url: "https://cbellinger27.github.io"
baseurl: "/RobuO"


markdown: kramdown
theme: null


plugins:
  - jekyll-feed

collections:
  people:
    output: true
