title: RobuO
description: Intelligent Robotics and Control at uOttawa

baseurl: "https://iara-lab.github.io"
url: "RobuO"


markdown: kramdown
theme: null


plugins:
  - jekyll-feed

collections:
  people:
    output: true
